import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as XLSX from 'xlsx';

import { CategorySales, Order, SalesMetrics } from '../types/models';
import { formatDateTime } from '../utils/date';

interface ExportPayload {
  rangeLabel: string;
  generatedBy: string;
  metrics: SalesMetrics;
  categorySales: CategorySales[];
  transactions: Order[];
}

const BRAND_LOGO = require('../../assets/suki-send-logo.png');

function buildTimestamp() {
  const now = new Date();
  return `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(
    now.getHours(),
  ).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}`;
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

async function shareFile(uri: string, mimeType: string, dialogTitle: string) {
  const canShare = await Sharing.isAvailableAsync();
  if (!canShare) {
    throw new Error('File sharing is not available on this device.');
  }

  await Sharing.shareAsync(uri, {
    mimeType,
    dialogTitle,
  });
}

async function getBrandLogoDataUri() {
  try {
    const asset = Asset.fromModule(BRAND_LOGO);
    if (!asset.localUri) {
      await asset.downloadAsync();
    }

    const sourceUri = asset.localUri ?? asset.uri;
    if (!sourceUri) {
      return null;
    }

    const base64 = await FileSystem.readAsStringAsync(sourceUri, {
      encoding: FileSystem.EncodingType.Base64,
    });
    return `data:image/png;base64,${base64}`;
  } catch {
    return null;
  }
}

function buildWorkbook(payload: ExportPayload) {
  const workbook = XLSX.utils.book_new();

  const summaryRows: Array<Array<string | number>> = [
    ['SUKI SEND'],
    ['From Store to Door, Ka Suki'],
    ['Brand Logo Asset', 'suki-send-logo.png'],
    [],
    ['Range', payload.rangeLabel],
    ['Generated By', payload.generatedBy],
    ['Generated At', new Date().toLocaleString()],
    [],
    ['Gross Sales', payload.metrics.grossSales],
    ['Profit', payload.metrics.profit],
    ['Paid Orders', payload.metrics.totalOrders],
    ['Average Order Value', payload.metrics.averageOrderValue],
    ['Top Selling Product', payload.metrics.topSellingProduct],
    ['Low Stock Items', payload.metrics.lowStockCount],
  ];
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryRows);
  summarySheet['!cols'] = [{ wch: 28 }, { wch: 32 }];
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

  const categoryRows = payload.categorySales.length
    ? payload.categorySales.map((entry) => [entry.category, entry.sales])
    : [['No category sales data', 0]];
  const categorySheet = XLSX.utils.aoa_to_sheet([
    ['Category', 'Sales'],
    ...categoryRows,
  ]);
  categorySheet['!cols'] = [{ wch: 28 }, { wch: 16 }];
  XLSX.utils.book_append_sheet(workbook, categorySheet, 'Category Sales');

  const transactionRows = payload.transactions.length
    ? payload.transactions.map((order) => [
        order.orderNo,
        formatDateTime(order.createdAt),
        order.status,
        order.deliveryArea,
        order.total,
      ])
    : [['No paid transactions found', '', '', '', 0]];
  const transactionsSheet = XLSX.utils.aoa_to_sheet([
    ['Order No', 'Date', 'Status', 'Delivery Area', 'Total'],
    ...transactionRows,
  ]);
  transactionsSheet['!cols'] = [{ wch: 16 }, { wch: 22 }, { wch: 16 }, { wch: 28 }, { wch: 14 }];
  XLSX.utils.book_append_sheet(workbook, transactionsSheet, 'Transactions');

  return workbook;
}

export async function exportSalesReportXLSX(payload: ExportPayload) {
  const timestamp = buildTimestamp();
  const fileUri = `${FileSystem.documentDirectory}suki-send-sales-${timestamp}.xlsx`;
  const workbook = buildWorkbook(payload);
  const contentBase64 = XLSX.write(workbook, { bookType: 'xlsx', type: 'base64' });

  await FileSystem.writeAsStringAsync(fileUri, contentBase64, {
    encoding: FileSystem.EncodingType.Base64,
  });

  await shareFile(
    fileUri,
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'Export Sales Report (Excel/XLSX)',
  );
}

export const exportSalesReportCSV = exportSalesReportXLSX;

function buildReportHtml(payload: ExportPayload, logoDataUri: string | null) {
  const transactionRows = payload.transactions.length
    ? payload.transactions
        .map(
          (order) => `
      <tr>
        <td>${escapeHtml(order.orderNo)}</td>
        <td>${escapeHtml(formatDateTime(order.createdAt))}</td>
        <td>${escapeHtml(order.status)}</td>
        <td>${escapeHtml(order.deliveryArea)}</td>
        <td>PHP ${order.total.toFixed(2)}</td>
      </tr>
    `,
        )
        .join('')
    : `
      <tr>
        <td colspan="5">No paid transactions for this range.</td>
      </tr>
    `;

  const categoryRows = payload.categorySales.length
    ? payload.categorySales
        .map(
          (entry) => `
      <tr>
        <td>${escapeHtml(entry.category)}</td>
        <td>PHP ${entry.sales.toFixed(2)}</td>
      </tr>
    `,
        )
        .join('')
    : `
      <tr>
        <td colspan="2">No category sales data.</td>
      </tr>
    `;

  const logoHtml = logoDataUri
    ? `<img class="logo" src="${logoDataUri}" alt="SUKI SEND logo" />`
    : `<div class="logo-fallback">SUKI SEND</div>`;

  return `
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body {
          font-family: Arial, sans-serif;
          padding: 20px;
          color: #1f2937;
        }
        .header {
          border-bottom: 2px solid #f97316;
          padding-bottom: 12px;
          margin-bottom: 18px;
          display: flex;
          gap: 14px;
          align-items: center;
        }
        .logo {
          width: 72px;
          height: 72px;
          object-fit: contain;
        }
        .logo-fallback {
          width: 72px;
          height: 72px;
          border-radius: 10px;
          background: #f97316;
          color: #fff;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 12px;
          font-weight: 700;
          text-align: center;
          padding: 6px;
          box-sizing: border-box;
        }
        .title {
          font-size: 24px;
          margin: 0;
          color: #f97316;
        }
        .subtitle {
          margin: 4px 0;
          color: #475569;
        }
        .metrics {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 8px;
          margin-bottom: 16px;
        }
        .metric-card {
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          padding: 10px;
        }
        .metric-label {
          font-size: 12px;
          color: #64748b;
          margin-bottom: 4px;
        }
        .metric-value {
          font-size: 16px;
          font-weight: 700;
        }
        h3 {
          margin: 16px 0 8px;
          color: #0f172a;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 6px;
        }
        th, td {
          border: 1px solid #e2e8f0;
          padding: 8px;
          font-size: 12px;
          text-align: left;
        }
        th {
          background: #f8fafc;
        }
      </style>
    </head>
    <body>
      <div class="header">
        ${logoHtml}
        <div>
          <h1 class="title">SUKI SEND - Sales Performance Report</h1>
          <p class="subtitle">Range: ${escapeHtml(payload.rangeLabel)}</p>
          <p class="subtitle">Generated by: ${escapeHtml(payload.generatedBy)}</p>
          <p class="subtitle">Generated at: ${escapeHtml(new Date().toLocaleString())}</p>
        </div>
      </div>

      <div class="metrics">
        <div class="metric-card">
          <div class="metric-label">Gross Sales</div>
          <div class="metric-value">PHP ${payload.metrics.grossSales.toFixed(2)}</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Paid Orders</div>
          <div class="metric-value">${payload.metrics.totalOrders}</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Profit</div>
          <div class="metric-value">PHP ${payload.metrics.profit.toFixed(2)}</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Top Selling Product</div>
          <div class="metric-value">${escapeHtml(payload.metrics.topSellingProduct)}</div>
        </div>
      </div>

      <h3>Sales By Category</h3>
      <table>
        <thead>
          <tr>
            <th>Category</th>
            <th>Sales</th>
          </tr>
        </thead>
        <tbody>
          ${categoryRows}
        </tbody>
      </table>

      <h3>Paid COD Transactions</h3>
      <table>
        <thead>
          <tr>
            <th>Order No</th>
            <th>Date</th>
            <th>Status</th>
            <th>Delivery Area</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          ${transactionRows}
        </tbody>
      </table>
    </body>
  </html>
  `;
}

export async function exportSalesReportPDF(payload: ExportPayload) {
  const logoDataUri = await getBrandLogoDataUri();
  const html = buildReportHtml(payload, logoDataUri);
  const file = await Print.printToFileAsync({ html });

  await shareFile(file.uri, 'application/pdf', 'Export Sales Report (PDF)');
}
