// Web version: uses Blob download for CSV and window.print() for PDF
import { CategorySales, Order, SalesMetrics } from '../types/models';
import { formatDateTime } from '../utils/date';

interface ExportPayload {
    rangeLabel: string;
    generatedBy: string;
    metrics: SalesMetrics;
    categorySales: CategorySales[];
    transactions: Order[];
}

function buildTimestamp() {
    const now = new Date();
    return `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(
        now.getHours(),
    ).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}`;
}

function downloadBlob(content: string, fileName: string, mimeType: string) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

export async function exportSalesReportCSV(payload: ExportPayload) {
    const timestamp = buildTimestamp();
    const lines = [
        'SUKI SEND SALES REPORT',
        `Range,${payload.rangeLabel}`,
        `Generated By,${payload.generatedBy}`,
        `Generated At,${new Date().toISOString()}`,
        '',
        'Summary',
        'Gross Sales,Profit,Total Orders,Top Selling Product,Low Stock Items',
        `${payload.metrics.grossSales},${payload.metrics.profit},${payload.metrics.totalOrders},${payload.metrics.topSellingProduct},${payload.metrics.lowStockCount}`,
        '',
        'Category Sales',
        'Category,Sales',
        ...payload.categorySales.map((entry) => `${entry.category},${entry.sales}`),
        '',
        'Recent COD Transactions',
        'Order No,Date,Status,Delivery Area,Total',
        ...payload.transactions.map(
            (order) => `${order.orderNo},${formatDateTime(order.createdAt)},${order.status},${order.deliveryArea},${order.total}`,
        ),
    ];
    downloadBlob(lines.join('\n'), `suki-send-sales-${timestamp}.csv`, 'text/csv');
}

function buildReportHtml(payload: ExportPayload) {
    const transactionRows = payload.transactions
        .map(
            (order) => `
      <tr>
        <td>${order.orderNo}</td>
        <td>${formatDateTime(order.createdAt)}</td>
        <td>${order.status}</td>
        <td>${order.deliveryArea}</td>
        <td>PHP ${order.total.toFixed(2)}</td>
      </tr>
    `,
        )
        .join('');

    const categoryRows = payload.categorySales
        .map(
            (entry) => `
      <tr>
        <td>${entry.category}</td>
        <td>PHP ${entry.sales.toFixed(2)}</td>
      </tr>
    `,
        )
        .join('');

    return `
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; color: #1f2937; }
        .header { border-bottom: 2px solid #f97316; padding-bottom: 10px; margin-bottom: 18px; }
        .title { font-size: 24px; margin: 0; color: #f97316; }
        .subtitle { margin: 4px 0; color: #475569; }
        .metrics { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; margin-bottom: 16px; }
        .metric-card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px; }
        .metric-label { font-size: 12px; color: #64748b; margin-bottom: 4px; }
        .metric-value { font-size: 16px; font-weight: 700; }
        h3 { margin: 16px 0 8px; color: #0f172a; }
        table { width: 100%; border-collapse: collapse; margin-top: 6px; }
        th, td { border: 1px solid #e2e8f0; padding: 8px; font-size: 12px; text-align: left; }
        th { background: #f8fafc; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1 class="title">SUKI SEND - Sales Performance Report</h1>
        <p class="subtitle">Range: ${payload.rangeLabel}</p>
        <p class="subtitle">Generated by: ${payload.generatedBy}</p>
        <p class="subtitle">Generated at: ${new Date().toLocaleString()}</p>
      </div>
      <div class="metrics">
        <div class="metric-card">
          <div class="metric-label">Gross Sales</div>
          <div class="metric-value">PHP ${payload.metrics.grossSales.toFixed(2)}</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Total Orders</div>
          <div class="metric-value">${payload.metrics.totalOrders}</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Profit</div>
          <div class="metric-value">PHP ${payload.metrics.profit.toFixed(2)}</div>
        </div>
        <div class="metric-card">
          <div class="metric-label">Top Selling Product</div>
          <div class="metric-value">${payload.metrics.topSellingProduct}</div>
        </div>
      </div>
      <h3>Sales By Category</h3>
      <table>
        <thead><tr><th>Category</th><th>Sales</th></tr></thead>
        <tbody>${categoryRows}</tbody>
      </table>
      <h3>Recent COD Transactions</h3>
      <table>
        <thead><tr><th>Order No</th><th>Date</th><th>Status</th><th>Delivery Area</th><th>Total</th></tr></thead>
        <tbody>${transactionRows}</tbody>
      </table>
    </body>
  </html>
  `;
}

export async function exportSalesReportPDF(payload: ExportPayload) {
    const html = buildReportHtml(payload);
    const printWindow = window.open('', '_blank');
    if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();
        printWindow.focus();
        printWindow.print();
    }
}
